//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPOITMENTS
    {
        public int APPOITMENT_ID { get; set; }
        public System.DateTime APPOITMENT_DATE { get; set; }
        public int CLIENT_ID { get; set; }
        public int CLIENT_CAR_ID { get; set; }
    
        public virtual Clients Clients { get; set; }
    }
}
