//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTS_LINK
    {
        public int LINK_ID { get; set; }
        public Nullable<int> PART_ID { get; set; }
        public string URL { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE { get; set; }
        public Nullable<int> THREAD { get; set; }
    }
}
