//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICES
    {
        public int SERVICE_ID { get; set; }
        public string SERVICE_NAME { get; set; }
        public Nullable<double> PRICE_PER_HOUR { get; set; }
        public string DESCRIPTION { get; set; }
    }
}
