//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Car_Model_Part
    {
        public string Car_Model { get; set; }
        public string Model_Name { get; set; }
        public int Part_ID { get; set; }
        public string Part_Name { get; set; }
        public Nullable<double> Part_price { get; set; }
        public string Part_details { get; set; }
        public string Part_Manuf { get; set; }
        public int Car_ID { get; set; }
        public int Model_ID { get; set; }
    }
}
