delete EMPLOYEES_SERVICE_WORKS
delete SERVICE_WORK_PARTS
delete SERVICE_WORKS
DELETE Parts
DELETE APPOITMENTS
DELETE CLIENT_CARS
DELETE EMPLOYEES
DELETE CLIENTS
update GENERATORS
--set GENERATOR_VALUE = 0
exec sp_updatestats


UPDATE GENERATORS
SET GENERATOR_VALUE = (SELECT MAX(CAR_ID) FROM Cars)
WHERE GENERATOR_NAME = 'Cars'


UPDATE GENERATORS
SET GENERATOR_VALUE = (SELECT MAX(MODEL_ID) FROM MODELS)
WHERE GENERATOR_NAME = 'Models'