delete EMPLOYEES_SERVICE_WORKS
delete SERVICE_WORK_PARTS
delete SERVICE_WORKS
DELETE Parts
DELETE APPOITMENTS
DELETE CLIENT_CARS
delete SUB_MODELS
delete models
delete cars
update GENERATORS
set GENERATOR_VALUE = 0