IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[VIEW_APPOITMENT_INVOICE_DATA]') AND OBJECTPROPERTY(id, N'IsView') = 1)
	BEGIN
		PRINT 'Dropping View VIEW_APPOITMENT_INVOICE_DATA'
    DROP VIEW [dbo].VIEW_APPOITMENT_INVOICE_DATA
  END
GO

PRINT 'Creating View VIEW_APPOITMENT_INVOICE_DATA'
GO
CREATE VIEW VIEW_APPOITMENT_INVOICE_DATA
AS
	SELECT  SW.APPOITMENT_ID, QUANTITY,SW.SERVICE_WORK_ID, S.SERVICE_NAME, SW.WORK_PRICE, MES.ITEM_NAME AS MEASURE,
		SW.TOTAL_PRICE
	FROM SERVICE_WORKS SW
	INNER JOIN SERVICES S ON (S.SERVICE_ID = SW.SERVICE_ID)
	INNER JOIN LOOKUP_ITEMS MES ON (SW.MEASURE = MES.ITEM_CODE)
	WHERE SW.INCLUDE_INVOICE = 'Y'
	UNION ALL
	SELECT SW.APPOITMENT_ID, SWP.QUANTITY,SWP.SERVICE_WORK_ID, P.part_name, ISNULL(SWP.PART_PRICE, P.part_price),
		MES.ITEM_NAME AS MEASURE, SWP.TOTAL_PRICE
	FROM SERVICE_WORKS SW
	INNER JOIN SERVICE_WORK_PARTS SWP ON (SW.SERVICE_WORK_ID = SWP.SERVICE_WORK_ID)
	INNER JOIN PARTS P ON (SWP.PART_ID = P.PART_ID)
	INNER JOIN LOOKUP_ITEMS MES ON (SWP.MEASURE = MES.ITEM_CODE)
	WHERE SWP.INCLUDE_INVOICE = 'Y' AND SW.INCLUDE_INVOICE = 'Y'
	
GO
   