Create view VIEW_CLIENT_CARS as
select 
CLC.CLIENT_CAR_ID, CLC.CLIENT_ID, CLC.MODEL_ID, CLC.CAR_YEAR, CLC.ENGINE_TYPE, CLC.ENGINE_SIZE
, M.MODEL_NAME, L.ITEM_NAME AS ENGINE_TYPE_DESCR
from CLIENT_CARS CLC
INNER JOIN MODELS M ON (M.MODEL_ID = CLC.MODEL_ID)
INNER JOIN LOOKUP_ITEMS L ON (CLC.ENGINE_TYPE = L.ITEM_CODE)
