CREATE TABLE APPOITMENTS
(
	APPOITMENT_ID INT NOT NULL PRIMARY KEY,
	APPOITMENT_DATE DATETIME NOT NULL ,
	CLIENT_ID INT NOT NULL,
	CLIENT_CAR_ID INT NOT NULL
	CONSTRAINT FK_APPOITMENTS_CLIENT_ID FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(CLIENT_ID),
	CONSTRAINT FK_APPOITMENTS_CLIENT_ID FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(CLIENT_ID)
	CONSTRAINT FK_APPOITMENT_CLIENT_CAR_ID FOREIGN KEY (CLIENT_CAR_ID) REFERENCES CLIENT_CARS(CLIENT_CAR_ID)
)