CREATE TABLE APPOITMENTS
(
	APPOITMENT_ID INT NOT NULL PRIMARY KEY,
	APPOITMENT_DATE DATETIME NOT NULL ,
	CLIENT_ID INT NOT NULL,
	CLIENT_CAR_ID INT NOT NULL
	CONSTRAINT FK_APPOITMENTS_CLIENT_ID FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(CLIENT_ID)
)