CREATE TABLE CLIENT_CARS
(
	CLIENT_CAR_ID INT NOT NULL PRIMARY KEY,
	CLIENT_ID INT NOT NULL,
	CAR_ID INT NOT NULL,
	MODEL_ID INT NOT NULL,
	CAR_YEAR INT NULL,
	ENGINE_TYPE VARCHAR(20) NULL,
	ENGINE_SIZE FLOAT NULL,
	CONSTRAINT FK_CLIENT_CARS_CLIENTS FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(CLIENT_ID),
	CONSTRAINT FK_CLIENT_CARS_MODELS FOREIGN KEY (MODEL_ID) REFERENCES MODELS(MODEL_ID),
	CONSTRAINT FK_CLIENT_CARS_ENG_LOOKUP_ITEMS FOREIGN KEY (ENGINE_TYPE) REFERENCES LOOKUP_ITEMS(ITEM_CODE)
)
