Create Table Clients
(
	CLIENT_ID int NOT NULL Primary key,
	CLIENT_NAME varchar(100),
	CLIENT_FORM DATETIME,
	TELEPHONE VARCHAR(25),
	EMAIL VARCHAR(100),
	DETAILS VARCHAR(500),
	CLIENT_TYPE VARCHAR(20) NOT NULL,
	CONSTRAINT FK_CLIENTS_TYPE_LOOKUP FOREIGN KEY (CLIENT_TYPE) REFERENCES LOOKUP_ITEMS(ITEM_CODE)
)
