Create Table Clients
(
	CLIENT_ID int NOT NULL Primary key,
	CLIENT_NAME varchar(100),
	CLIENT_FORM DATETIME,
	COMPANY VARCHAR(1),
	TELEPHONE VARCHAR(25),
	EMAIL VARCHAR(100),
	DETAILS VARCHAR(500)
)
