CREATE TABLE EMPLOYEES_SERVICE_WORKS
(
	EMPLOYEE_WORK_ID INT NOT NULL PRIMARY KEY,
	SERVICE_WORK_ID INT NOT NULL,
	EMPLOYEE_ID INT NOT NULL,
	CONSTRAINT FK_EMPL_SERV_WORKS_SERVICE_WORKS FOREIGN KEY (SERVICE_WORK_ID) REFERENCES SERVICE_WORKS(SERVICE_WORK_ID),
	CONSTRAINT FK_EMPL_SERV_WORKS_EMPL_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
)
