CREATE TABLE EMPLOYEES
(
	EMPLOYEE_ID INT NOT NULL PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	EMPL_TYPE VARCHAR(20) NOT NULL,
	TELEPHONE VARCHAR(25),
	EMAIL VARCHAR(100),
	DETAILS VARCHAR(500),
	DATE_EMPLOYEE DATETIME NOT NULL,
	QUIT_DATE DATETIME,
	CONSTRAINT FK_EMPL_TYPE_LOOKUP FOREIGN KEY (EMPL_TYPE) REFERENCES LOOKUP_ITEMS(ITEM_CODE),
	
)

