CREATE TABLE LOOKUP_ITEMS
(
	L_ITEM_ID INT NOT NULL,
	LOOKUP_NAME VARCHAR(15) NOT NULL,
	ITEM_CODE VARCHAR(20) NOT NULL PRIMARY_KEY,
	ITEM_NAME VARCHAR(30) NULL,
	ITEM_DESCRIPT VARCHAR(100) NULL
	UNIQUE (ITEM_CODE)
)
