CREATE TABLE SERVICE_WORK_PARTS
(
	WORK_PART_ID INT NOT NULL PRIMARY KEY,
	SERVICE_WORK_ID INT NOT NULL,
	PART_ID INT NOT NULL,
	CONSTRAINT FK_S_WORK_PART_SERVICEWORKS FOREIGN KEY (SERVICE_WORK_ID) REFERENCES SERVICE_WORKS(SERVICE_WORK_ID),
	CONSTRAINT FK_SERV_WORK_PART_PARTS FOREIGN KEY (PART_ID) REFERENCES PARTS(PART_ID)
)

