CREATE TABLE SERVICE_WORKS
(
	SERVICE_WORK_ID INT NOT NULL PRIMARY KEY,
	APPOITMENT_ID INT NOT NULL,
	WORK_STATUS VARCHAR(20) NOT NULL,
	WORK_PRICE FLOAT,
	CONSTRAINT FK_SERVICE_WORK_APPOITMENT_ID FOREIGN KEY (APPOITMENT_ID) REFERENCES APPOITMENTS(APPOITMENT_ID),
	CONSTRAINT FK_SERVICE_WORKS_STATUS_LOOKUP FOREIGN KEY (WORK_STATUS) REFERENCES LOOKUP_ITEMS(ITEM_CODE)
)

INSERT INTO LOOKUP_ITEMS(L_ITEM_ID, LOOKUP_NAME, ITEM_CODE, ITEM_NAME, ITEM_DESCRIPT)
VALUES(3, 'work_status', 'work_st_pend', 'Чакащ', 'Чакащ')

INSERT INTO LOOKUP_ITEMS(L_ITEM_ID, LOOKUP_NAME, ITEM_CODE, ITEM_NAME, ITEM_DESCRIPT)
VALUES(4, 'work_status', 'work_st_started', 'В процес', 'В процес на работа')


INSERT INTO LOOKUP_ITEMS(L_ITEM_ID, LOOKUP_NAME, ITEM_CODE, ITEM_NAME, ITEM_DESCRIPT)
VALUES(4, 'work_status', 'work_st_finished', 'Приключен', 'Приключен)