CREATE TABLE EMPOLOYEES
(
	EMPLOYEE_ID INT NOT NULL PRIMARY KEY,
	CLIENT_ID INT NOT NULL,
	DATE_EMPLOYEE DATETIME NOT NULL,
	QUIT_DATE DATETIME,
	CONSTRAINT FK_EMPLOYEE_CLIENTS FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(CLIENT_ID)
)

