CREATE TABLE SERVICE_WORKS
(
	SERVICE_WORK_ID INT NOT NULL PRIMARY KEY,
	APPOITMENT_ID INT NOT NULL,
	SERVICE_ID INT NOT NULL,
	WORK_STATUS VARCHAR(20) NOT NULL,
	TIME_START DATETIME,
	TIME_FINISH DATETIME,
	WORK_PRICE FLOAT,
	CONSTRAINT FK_SERVICE_WORK_APPOITMENT_ID FOREIGN KEY (APPOITMENT_ID) REFERENCES APPOITMENTS(APPOITMENT_ID),
	CONSTRAINT FK_SERVICE_WORKS_STATUS_LOOKUP FOREIGN KEY (WORK_STATUS) REFERENCES LOOKUP_ITEMS(ITEM_CODE),
	CONSTRAINT FK_SERVICE_WORKS_SERVICES FOREIGN KEY (SERVICE_ID) REFERENCES SERVICES(SERVICE_ID)
)
