CREATE TABLE SUB_MODELS
(
	SUB_MODEL_ID INT NOT NULL PRIMARY KEY,
	MODEL_ID INT NOT NULL,
	YEAR_MANUF INT NOT NULL,
	YEAR_STOP INT,
	CONSTRAINT FK_SUB_MODEL_MODELS FOREIGN KEY (MODEL_ID) REFERENCES MODELS(MODEL_ID)
)
