//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPartDataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEES()
        {
            this.EMPLOYEES_SERVICE_WORKS = new HashSet<EMPLOYEES_SERVICE_WORKS>();
        }
    
        public int EMPLOYEE_ID { get; set; }
        public string NAME { get; set; }
        public string EMPL_TYPE { get; set; }
        public string TELEPHONE { get; set; }
        public string EMAIL { get; set; }
        public string DETAILS { get; set; }
        public System.DateTime DATE_EMPLOYEE { get; set; }
        public Nullable<System.DateTime> QUIT_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYEES_SERVICE_WORKS> EMPLOYEES_SERVICE_WORKS { get; set; }
        public virtual LOOKUP_ITEMS LOOKUP_ITEMS { get; set; }
    }
}
