//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPartDataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEES_SERVICE_WORKS
    {
        public int EMPLOYEE_WORK_ID { get; set; }
        public int SERVICE_WORK_ID { get; set; }
        public int EMPLOYEE_ID { get; set; }
    
        public virtual EMPLOYEES EMPLOYEES { get; set; }
        public virtual SERVICE_WORKS SERVICE_WORKS { get; set; }
    }
}
