//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPartDataModels
{
    using System;
    
    public partial class FUN_CALC_APP_SUM_BY_APP_ID_Result1
    {
        public int APPOITMENT_ID { get; set; }
        public int SERVICE_WORK_ID { get; set; }
        public string SERVICE_NAME { get; set; }
        public string PART_NAME { get; set; }
        public string PART_MANUF { get; set; }
        public Nullable<double> WORK_PRICE { get; set; }
        public Nullable<double> QUANTITY { get; set; }
    }
}
