//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPartDataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Cars_Models
    {
        public int CAR_ID { get; set; }
        public string Car_Model { get; set; }
        public string Model_name { get; set; }
        public int Model_ID { get; set; }
    }
}
