//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPartDataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_APPOITMENT_INVOICE_DATA
    {
        public int APPOITMENT_ID { get; set; }
        public double QUANTITY { get; set; }
        public int SERVICE_WORK_ID { get; set; }
        public string SERVICE_NAME { get; set; }
        public Nullable<double> WORK_PRICE { get; set; }
        public string MEASURE { get; set; }
        public Nullable<double> TOTAL_PRICE { get; set; }
    }
}
