IF EXISTS (SELECT * FROM SYSOBJECTS WHERE XTYPE IN ('FN', 'IF', 'TF') AND NAME = 'FUN_CALC_APP_SUM_BY_APP_ID')
	BEGIN
		PRINT 'DROPPING FUNCTION FUN_CALC_APP_SUM_BY_APP_ID'
		DROP  FUNCTION DBO.FUN_CALC_APP_SUM_BY_APP_ID
	END
GO 

PRINT 'CREATING FUNCTION FUN_CALC_APP_SUM_BY_APP_ID'
GO

CREATE FUNCTION FUN_CALC_APP_SUM_BY_APP_ID(@APPOITMENT_ID INT)
RETURNS TABLE
RETURN
	SELECT top 10000 *
	FROM VIEW_APPOITMENT_CLIENT_SUMS
	WHERE APPOITMENT_ID = @APPOITMENT_ID
	ORDER BY APPOITMENT_ID
	UNION ALL
	SELECT '', '', '', '','Обща Сума:' AS TOTAL_SUM, SUM(WORK_PRICE)
	FROM VIEW_APPOITMENT_CLIENT_SUMS
	WHERE APPOITMENT_ID = @APPOITMENT_ID
	GROUP BY APPOITMENT_ID
	 
GO
