IF EXISTS (SELECT * FROM SYSOBJECTS WHERE XTYPE IN ('FN', 'IF', 'TF') AND NAME = 'FUN_INVOICE_TOTAL_SUM_BY_APP_ID')
	BEGIN
		PRINT 'DROPPING FUNCTION FUN_INVOICE_TOTAL_SUM_BY_APP_ID'
		DROP  FUNCTION DBO.FUN_INVOICE_TOTAL_SUM_BY_APP_ID
	END
GO 
PRINT 'CREATING FUNCTION FUN_INVOICE_TOTAL_SUM_BY_APP_ID'
GO

CREATE FUNCTION FUN_INVOICE_TOTAL_SUM_BY_APP_ID(@APPOITMENT_ID INT)
RETURNS TABLE
RETURN
	SELECT SUM(TOTAL_PRICE) AS TOTAL_PRICE
	FROM VIEW_APPOITMENT_INVOICE_DATA
	WHERE APPOITMENT_ID = @APPOITMENT_ID
	GROUP BY APPOITMENT_ID
	 
GO
