IF EXISTS (SELECT * FROM SYSOBJECTS WHERE XTYPE IN ('FN', 'IF', 'TF') AND NAME = 'FUN_INVOICE_DATA_BY_APP_ID')
	BEGIN
		PRINT 'DROPPING FUNCTION FUN_INVOICE_DATA_BY_APP_ID'
		DROP  FUNCTION DBO.FUN_INVOICE_DATA_BY_APP_ID
	END
GO 
PRINT 'CREATING FUNCTION FUN_INVOICE_DATA_BY_APP_ID'
GO

CREATE FUNCTION FUN_INVOICE_DATA_BY_APP_ID(@APPOITMENT_ID INT)
RETURNS TABLE
RETURN
	SELECT top 10000 ROW_NUMBER() OVER(ORDER BY APPOITMENT_ID DESC) AS Row, *
	FROM VIEW_APPOITMENT_INVOICE_DATA
	WHERE APPOITMENT_ID = @APPOITMENT_ID
	ORDER BY APPOITMENT_ID
	/*UNION ALL
	SELECT ROW_NUMBER() OVER(ORDER BY APPOITMENT_ID DESC) AS Row, 
	NULL, NULL,'','Oбща —ума:' AS TOTAL_SUM, SUM(WORK_PRICE), '' AS MEASURE, NULL
	FROM VIEW_APPOITMENT_INVOICE_DATA
	WHERE APPOITMENT_ID = @APPOITMENT_ID
	GROUP BY APPOITMENT_ID*/
	 
GO
