//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestService.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IParts")]
    public interface IParts {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParts/UpdatePartByID", ReplyAction="http://tempuri.org/IParts/UpdatePartByIDResponse")]
        string UpdatePartByID(int iPartID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPartsChannel : TestService.ServiceReference1.IParts, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PartsClient : System.ServiceModel.ClientBase<TestService.ServiceReference1.IParts>, TestService.ServiceReference1.IParts {
        
        public PartsClient() {
        }
        
        public PartsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PartsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PartsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PartsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string UpdatePartByID(int iPartID) {
            return base.Channel.UpdatePartByID(iPartID);
        }
    }
}
