ALTER TABLE SERVICE_WORK_PARTS
ADD QUANTITY FLOAT NOT NULL
GO

ALTER TABLE SERVICE_WORK_PARTS
ADD MEASURE VARCHAR(20) NULL,
	CONSTRAINT FK_SERV_WORK_PARTS_LOOKUP_MEASURE FOREIGN KEY (MEASURE)
	REFERENCES LOOKUP_ITEMS(ITEM_CODE)
GO

UPDATE SERVICE_WORK_PARTS 
SET MEASURE = 'measure_numb'

ALTER TABLE SERVICE_WORK_PARTS
ALTER COLUMN MEASURE VARCHAR(20) NOT NULL

ALTER TABLE SERVICE_WORK_PARTS
ADD TOTAL_PRICE FLOAT

ALTER TABLE SERVICE_WORK_PARTS
ADD INCLUDE_INVOICE VARCHAR(1)
GO
UPDATE SERVICE_WORK_PARTS
SET INCLUDE_INVOICE = 'Y'
GO
ALTER TABLE SERVICE_WORK_PARTS
ALTER COLUMN INCLUDE_INVOICE VARCHAR(1) NOT NULL
GO

ALTER TABLE SERVICE_WORK_PARTS
ADD DISPL_MANUF_WORK_CARD VARCHAR(1)
GO
UPDATE SERVICE_WORK_PARTS
SET DISPL_MANUF_WORK_CARD = 'Y'
GO
ALTER TABLE SERVICE_WORK_PARTS
ALTER COLUMN DISPL_MANUF_WORK_CARD VARCHAR(1) NOT NULL
GO