
ALTER TABLE SERVICE_WORKS
ADD QUANTITY FLOAT NULL
GO

UPDATE SERVICE_WORKS
SET QUANTITY = 1

ALTER TABLE SERVICE_WORKS
ALTER COLUMN QUANTITY FLOAT NOT NULL
GO



ALTER TABLE SERVICE_WORKS
ADD MEASURE VARCHAR(20) NULL,
	CONSTRAINT FK_SERV_WORK_LOOKUP_MEASURE FOREIGN KEY (MEASURE)
	REFERENCES LOOKUP_ITEMS(ITEM_CODE)
GO

UPDATE SERVICE_WORKS 
SET MEASURE = 'measure_numb'

ALTER TABLE SERVICE_WORKS
ALTER COLUMN MEASURE VARCHAR(20) NOT NULL

ALTER TABLE SERVICE_WORKS
ADD TOTAL_PRICE FLOAT

ALTER TABLE SERVICE_WORKS
ADD INCLUDE_INVOICE VARCHAR(1)
GO
UPDATE SERVICE_WORKS
SET INCLUDE_INVOICE = 'Y'
GO
ALTER TABLE SERVICE_WORKS
ALTER COLUMN INCLUDE_INVOICE VARCHAR(1) NOT NULL
GO