INSERT INTO LOOKUP_ITEMS(L_ITEM_ID, LOOKUP_NAME, ITEM_CODE, ITEM_NAME, ITEM_DESCRIPT) VALUES(16, 'measures', 'measure_numb', 'Бр.', 'Брой')
INSERT INTO LOOKUP_ITEMS(L_ITEM_ID, LOOKUP_NAME, ITEM_CODE, ITEM_NAME, ITEM_DESCRIPT) VALUES(17, 'measures', 'measure_liter', 'Л.', 'Литри')
INSERT INTO LOOKUP_ITEMS(L_ITEM_ID, LOOKUP_NAME, ITEM_CODE, ITEM_NAME, ITEM_DESCRIPT) VALUES(18, 'measures', 'measure_work_h', 'Раб. часове', 'Работни часове')

INSERT INTO LOOKUP_ITEMS(L_ITEM_ID, LOOKUP_NAME, ITEM_CODE, ITEM_NAME, ITEM_DESCRIPT) VALUES(19, 'paym_type', 'paym_t_cash', 'В брой', 'В брой')
INSERT INTO LOOKUP_ITEMS(L_ITEM_ID, LOOKUP_NAME, ITEM_CODE, ITEM_NAME, ITEM_DESCRIPT) VALUES(20, 'paym_type', 'paym_t_bank', 'По банков път', 'По банков път')

UPDATE GENERATORS
SET GENERATOR_VALUE = (SELECT MAX(SUB_MODEL_ID) from sub_models)
WHERE GENERATOR_NAME = 'SUBMODELS'