//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public Car()
        {
            this.Parts = new HashSet<Part>();
            this.Models = new HashSet<Model>();
        }
    
        public int Car_ID { get; set; }
        public string Car_Model { get; set; }
    
        public virtual ICollection<Part> Parts { get; set; }
        public virtual ICollection<Model> Models { get; set; }
    }
}
