//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceManagment
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class CarShopEntities1 : DbContext
    {
        public CarShopEntities1()
            : base("name=CarShopEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<APPOITMENT> APPOITMENTS { get; set; }
        public DbSet<Car> Cars { get; set; }
        public DbSet<Client> Clients { get; set; }
        public DbSet<LOOKUP_ITEMS> LOOKUP_ITEMS { get; set; }
        public DbSet<Model> Models { get; set; }
        public DbSet<Part> Parts { get; set; }
        public DbSet<PARTS_LINK> PARTS_LINK { get; set; }
        public DbSet<PROVIDER_CATEGORIES> PROVIDER_CATEGORIES { get; set; }
        public DbSet<REPAIR_SERVICES> REPAIR_SERVICES { get; set; }
        public DbSet<SERVICE> SERVICES { get; set; }
        public DbSet<SUB_CATEGORIES> SUB_CATEGORIES { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<VIEW_CLIENT_CARS> VIEW_CLIENT_CARS { get; set; }
        public DbSet<CLIENT_CARS> CLIENT_CARS { get; set; }
    
        [EdmFunction("CarShopEntities1", "FUN_YEARS_BETWEEN_LIST")]
        public virtual IQueryable<FUN_YEARS_BETWEEN_LIST_Result> FUN_YEARS_BETWEEN_LIST(Nullable<int> from, Nullable<int> to)
        {
            var fromParameter = from.HasValue ?
                new ObjectParameter("From", from) :
                new ObjectParameter("From", typeof(int));
    
            var toParameter = to.HasValue ?
                new ObjectParameter("To", to) :
                new ObjectParameter("To", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FUN_YEARS_BETWEEN_LIST_Result>("[CarShopEntities1].[FUN_YEARS_BETWEEN_LIST](@From, @To)", fromParameter, toParameter);
        }
    
        public virtual int SP_GEN_ID(string gENERATOR_NAME, Nullable<int> gENERATOR_STEP, ObjectParameter nEW_VALUE)
        {
            var gENERATOR_NAMEParameter = gENERATOR_NAME != null ?
                new ObjectParameter("GENERATOR_NAME", gENERATOR_NAME) :
                new ObjectParameter("GENERATOR_NAME", typeof(string));
    
            var gENERATOR_STEPParameter = gENERATOR_STEP.HasValue ?
                new ObjectParameter("GENERATOR_STEP", gENERATOR_STEP) :
                new ObjectParameter("GENERATOR_STEP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GEN_ID", gENERATOR_NAMEParameter, gENERATOR_STEPParameter, nEW_VALUE);
        }
    }
}
