//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.APPOITMENTS = new HashSet<APPOITMENT>();
            this.CLIENT_CARS = new HashSet<CLIENT_CARS>();
        }
    
        public int CLIENT_ID { get; set; }
        public string CLIENT_NAME { get; set; }
        public Nullable<System.DateTime> CLIENT_FORM { get; set; }
        public string COMPANY { get; set; }
        public string TELEPHONE { get; set; }
        public string EMAIL { get; set; }
        public string DETAILS { get; set; }
    
        public virtual ICollection<APPOITMENT> APPOITMENTS { get; set; }
        public virtual ICollection<CLIENT_CARS> CLIENT_CARS { get; set; }
    }
}
