//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model
    {
        public Model()
        {
            this.Parts = new HashSet<Part>();
            this.CLIENT_CARS = new HashSet<CLIENT_CARS>();
        }
    
        public int MODEL_ID { get; set; }
        public string MODEL_NAME { get; set; }
        public Nullable<int> YEAR_MANUF { get; set; }
        public Nullable<int> YEAR_STOP { get; set; }
        public Nullable<int> CAR_ID { get; set; }
        public string URL { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual ICollection<Part> Parts { get; set; }
        public virtual ICollection<CLIENT_CARS> CLIENT_CARS { get; set; }
    }
}
