//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICE_WORKS
    {
        public int SERVICE_WORK_ID { get; set; }
        public int APPOITMENT_ID { get; set; }
        public string WORK_STATUS { get; set; }
        public Nullable<double> WORK_PRICE { get; set; }
    
        public virtual APPOITMENTS APPOITMENTS { get; set; }
        public virtual LOOKUP_ITEMS LOOKUP_ITEMS { get; set; }
    }
}
