//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUB_CATEGORIES
    {
        public int SUB_CATEGORY_ID { get; set; }
        public int P_CATEGORY_ID { get; set; }
        public string S_CATEGORY_NAME { get; set; }
    }
}
