INSERT INTO Generators VALUES('PART_LINKS', 1)
insert into Generators values('Cars', 4)
insert into Generators values('Models', 3)
insert into Generators values('Parts', 1)
INSERT INTO GENERATORS VALUES('PART_ID', 0)
INSERT INTO GENERATORS VALUES('P_CATEGORY', 0)
INSERT INTO GENERATORS VALUES('S_CATEGORY', 0)
INSERT INTO GENERATORS VALUES('CLIENTS_CAR_ID', 0)

INSERT INTO GENERATORS VALUES('CLIENTS', 0)
INSERT INTO GENERATORS VALUES('APPOITMENTS_ID', 0)

INSERT INTO GENERATORS VALUES ('SERVICE_ID', 0)
INSERT INTO GENERATORS VALUES ('SERVICE_WORK_ID', 0)