ALTER TABLE APPOITMENTS
ADD APP_STATUS VARCHAR(20) NULL

UPDATE APPOITMENTS
SET APP_STATUS = 'app_st_act'

ALTER TABLE APPOITMENTS
ALTER COLUMN APP_STATUS VARCHAR(20) NOT NULL

ALTER TABLE APPOITMENTS
ADD CONSTRAINT FK_APP_ST_LOOKUPS FOREIGN KEY (APP_STATUS) REFERENCES LOOKUP_ITEMS(ITEM_CODE)