alter table clients
drop column CLIEN_TYPE

alter table clients
add CLIENT_TYPE VARCHAR(20)

update Clients
set CLIENT_TYPE = 'cl_type_private'

ALTER TABLE CLIENTS
ALTER COLUMN CLIENT_TYPE VARCHAR(20) NOT NULL

ALTER TABLE CLIENTS
ADD CONSTRAINT FK_CLIENTS_TYPE_LOOKUP FOREIGN KEY (CLIENT_TYPE) REFERENCES LOOKUP_ITEMS(ITEM_CODE)