//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clients()
        {
            this.APPOITMENTS = new HashSet<APPOITMENTS>();
            this.CLIENT_CARS = new HashSet<CLIENT_CARS>();
            this.EMPOLOYEES = new HashSet<EMPOLOYEES>();
        }
    
        public int CLIENT_ID { get; set; }
        public string CLIENT_NAME { get; set; }
        public Nullable<System.DateTime> CLIENT_FORM { get; set; }
        public string TELEPHONE { get; set; }
        public string EMAIL { get; set; }
        public string DETAILS { get; set; }
        public string CLIENT_TYPE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPOITMENTS> APPOITMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENT_CARS> CLIENT_CARS { get; set; }
        public virtual LOOKUP_ITEMS LOOKUP_ITEMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPOLOYEES> EMPOLOYEES { get; set; }
    }
}
