//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPOLOYEES
    {
        public int EMPLOYEE_ID { get; set; }
        public int CLIENT_ID { get; set; }
        public System.DateTime DATE_EMPLOYEE { get; set; }
        public Nullable<System.DateTime> QUIT_DATE { get; set; }
    
        public virtual Clients Clients { get; set; }
    }
}
